### ISSUE TITLE
Update downloadable CSV file

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#18]
Once the following have been computed and displayed in the grading page, they need to also be dumped into our CSV file:
- [x] Participation Score (number of likes given)
- [x] Participation Grade --> see issue #12 
- [x] Justifications Score (number of likes received)
- [x] Justifications Grade --> see issue #8
- [x] initial score
- [x] revised score

Discuss whether the following should be also part of the CSV of whether we just dump the grades computed based on the scores and these weights (the latter is most likely the way to go):
- [ ] weights for initial / revised / participation / justifications --> see issue #13 
- [ ] Limiting factor for MaxLikes --> see issue #16 issue #15

**Comment by profgrumpy** [comment]
Closed pending the new test scripts
