### ISSUE TITLE
Update Quiz Model

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#29]
Right now we have a few things that are hardcoded or re-tuned every time we load the grading page for a quiz.

- [x] Issue #12 (the threshold to receive participation points that are currently hardcoded) 
- [x] Issue #13 (the weights for each grade component)
- [x] Issue #15 (already done) 

We need to save these values in the Quiz model but let's do that AFTER we merge in the grading branch and deploy to test it out thoroughly. For the participation grade, that will entail adding some UI elements to the quiz editor.

**Comment by profgrumpy** [comment]
From now on, any feature that will need to update the model will mention it explicitly so this issue will be processed as the related issues are.
