### ISSUE TITLE
Update quiz editor based on the tunable parameters added to quiz grader

### ISSUE THREAD

**Issue by profgrumpy** [cereal-lab/EvoPIE#32]
We have added to the model (issue #29) and to the quiz grader page the following tunable parameters: 

- [x] Issue #12 (the threshold to receive participation points that are currently hardcoded) 
- [x] Issue #13 (the weights for each grade component)
- [x] Issue #15 (limiting factor) 

We should also add them to the quiz editor page so that an instructor can set the base values for these when the quiz is created / modified and save them in the model.

**Comment by neverdue** [comment]
Pushed a commit for this (6c90efe)
